name: Build & Publish Vite to GitHub Pages (no external actions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages

concurrency:
  group: gh-pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REPO: ${{ github.repository }}
      SHA:  ${{ github.sha }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # 1) Clone
      - name: Clone repository (auth via URL)
        run: |
          set -euo pipefail
          git init repo
          cd repo
          git remote add origin "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          git fetch --depth=1 origin "${SHA}"
          git checkout --detach "${SHA}"

      # 2) Node (20 LTS)
      - name: Install Node.js 20
        run: |
          set -e
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v && npm -v

      # 3) Build
      - name: Install deps
        working-directory: repo
        run: npm ci

      - name: Build
        working-directory: repo
        run: |
          npm run build
          cp dist/index.html dist/404.html || true

      # 4) Publish to gh-pages
      - name: Deploy to gh-pages
        working-directory: repo
        run: |
          set -euo pipefail
          rm -rf ../gh-pages && mkdir ../gh-pages
          cp -R dist/* ../gh-pages/
          cd ../gh-pages
          touch .nojekyll
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy ${SHA}"

          # Create branch if missing, then force-update it
          git branch -M gh-pages
          git remote add origin "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          git push -f origin gh-pages
